'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageSupplier

    '''<summary>
    '''ScriptManager2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager2 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btn_NewSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_NewSupplier As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_ChangePw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ChangePw As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FormSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddl_typeSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_typeSearch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_searchSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_searchSupplier As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_copy_Ora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_copy_Ora As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FormDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdf_supplierID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_supplierID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdf_FormStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_FormStatus As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lbl_form_sta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_form_sta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_SupplierCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SupplierCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_SupplierName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SupplierName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_SupplierNameTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SupplierNameTax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CordinatorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CordinatorName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_IDTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_IDTax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddl_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbl_form_sta2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_form_sta2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Phone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Usrname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Usrname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_PW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FormSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormSave As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btn_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Save As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_Cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Cancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''SqlDataSourceTab1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceTab1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btn_ResetPW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ResetPW As Global.System.Web.UI.WebControls.Button
End Class
