'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProfilePage

    '''<summary>
    '''LiteralAvatar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralAvatar As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralRole As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralFullName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralEmployeeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEmployeeID As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralEmail As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralDepartment As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralCompany As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralPosition As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralStartDate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralSalaryLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralSalaryLevel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralWorkStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralWorkStatus As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralWorkDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralWorkDays As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralProjectsCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralProjectsCompleted As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralRating As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''LiteralYearsInService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LiteralYearsInService As Global.System.Web.UI.WebControls.Literal
End Class
